# Generated by Django 6.0.1 on 2026-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=200)),
                ('peso', models.FloatField()),
                ('livello', models.IntegerField(default=1)),
                ('punti_salute', models.IntegerField()),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
