# Generated by Django 6.0.1 on 2026-01-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='peso',
        ),
    ]
